# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Date_Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Approved'), (1, 'Pending'), (3, 'Declined')], verbose_name='1: Pending, 2: Approved, 3:Declined')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_car', to='cars.Car')),
            ],
            options={
                'verbose_name': 'dato_reservasjon',
                'verbose_name_plural': 'dato_reservasjoner',
            },
        ),
        migrations.CreateModel(
            name='Registration_Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Fornavn')),
                ('last_name', models.CharField(max_length=100, verbose_name='Etternavn')),
                ('email', models.EmailField(max_length=100, verbose_name='Epost adresse')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telefonnummer')),
                ('misc_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ekstra informasjon')),
                ('date_made', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bil', to='cars.Car')),
                ('car_date_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.Car_Date_Reservation')),
            ],
            options={
                'verbose_name': 'kontakt_skjema',
                'verbose_name_plural': 'kontakt_skjermaer',
            },
        ),
    ]
