# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20161031_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservasjon', 'verbose_name_plural': 'Fullf\xf8rte Bestillinger'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dates_reserved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Leverings Dato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='initial_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Hente Dato'),
            preserve_default=False,
        ),
    ]
