# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20161117_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservasjon', 'verbose_name_plural': 'Reservasjoner'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bil', to='cars.Car', verbose_name='Bil'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kunde', to='booking.Customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Avsl\xe5tt'), (1, 'Ny'), (2, 'Godkjent')], verbose_name='Ordrestatus'),
        ),
    ]
