# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lock_reservation_period',
            options={'verbose_name': 'L\xe5st Periode', 'verbose_name_plural': 'L\xe5ste Perioder'},
        ),
    ]
