# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 14:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_panel', '0002_auto_20170716_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='lock_init_final_dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Startdato for stopp av hente/levering periode')),
                ('to_date', models.DateField(verbose_name='Sluttdato for stopp av hente/levering periode')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'L\xe5st hente/leverings periode',
                'verbose_name_plural': 'L\xe5ste hente/leverings perioder',
            },
        ),
    ]
