# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=70, verbose_name='Bilmerke')),
                ('model', models.CharField(max_length=70, verbose_name='Biltype')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(verbose_name='Antall seter')),
                ('fuel_type', models.CharField(max_length=20, verbose_name='Type drivstoff')),
                ('car_type', models.PositiveSmallIntegerField(verbose_name='Type bil, 1 = Personbil, 2 = Varebil, 3 ? Kombinertbil')),
            ],
        ),
    ]
