# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_accessories',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ekstra informasjon, splitt med komma (",")'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=250, verbose_name='Dagspris leie'),
        ),
    ]
