# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Approved'), (1, 'Pending'), (3, 'Declined')], verbose_name='1: Pending, 2: Approved, 3:Declined')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Personbil'), (2, 'Varebil'), (3, 'Kombibil')], verbose_name='Type bil, 1 = Personbil, 2 = Varebil, 3 ? Kombinertbil'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Bensin', 'Bensin')], max_length=20, verbose_name='Type drivstoff'),
        ),
        migrations.AddField(
            model_name='car_booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='cars.Car'),
        ),
    ]
