# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160912_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Bil', 'verbose_name_plural': 'Biler'},
        ),
        migrations.AlterModelOptions(
            name='car_booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookinger'},
        ),
        migrations.AddField(
            model_name='car',
            name='gallery_images',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilder til galleri. Splitt lenkene via komma ","'),
        ),
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.CharField(default='', max_length=50, verbose_name='Lenke til hovedbilde'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manuell', 'Manuell'), ('Automatgir', 'Automatgir')], default='Manuell', max_length=15, verbose_name='Gir'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Bensin', 'Bensin'), ('Hybrid', 'Hybrid'), ('Elbil', 'Elbil')], max_length=20, verbose_name='Type drivstoff'),
        ),
    ]
