# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20161019_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Skiltnummer'),
        ),
    ]
