# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 10:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20160920_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Fornavn')),
                ('last_name', models.CharField(max_length=100, verbose_name='Etternavn')),
                ('email', models.EmailField(max_length=100, verbose_name='Epost adresse')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telefonnummer')),
                ('misc_info', models.CharField(max_length=255, verbose_name='Ekstra informasjon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='cars.Car_Booking')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bil', to='cars.Car')),
            ],
        ),
    ]
