# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_registration_scheme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration_scheme',
            options={'verbose_name': 'Kontakt Skjema', 'verbose_name_plural': 'Kontakt Skjermaer'},
        ),
        migrations.AddField(
            model_name='registration_scheme',
            name='date_mate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Personbil'), (2, 'Varebil'), (3, 'Kombibil')], verbose_name='Kategori'),
        ),
    ]
