# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_for_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.Car')),
                ('thumbnail', models.CharField(default='', max_length=50, verbose_name='Lenke til mini bilde')),
                ('main_image', models.CharField(default='', max_length=50, verbose_name='Lenke til hovedbilde')),
                ('gallery_images', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bilder til galleri. Splitt lenkene via komma ","')),
            ],
            options={
                'verbose_name': 'Bil Bilder',
                'verbose_name_plural': 'Bil Bilder',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='car',
            name='main_image',
        ),
    ]
