# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20160924_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_scheme',
            old_name='date_mate',
            new_name='date_made',
        ),
        migrations.AlterField(
            model_name='registration_scheme',
            name='misc_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ekstra informasjon'),
        ),
    ]
