# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20170101_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(default='ab123', max_length=10, unique=True, verbose_name='Skiltnummer'),
            preserve_default=False,
        ),
    ]
